import {
  Accessibility,
  AlignLeft,
  AppWindow,
  ArrowLeftRight,
  ArrowUpDown,
  BadgeCheck,
  Baseline,
  Binary,
  Blend,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Building2,
  Circle,
  CircleDot,
  Clapperboard,
  Clock,
  Code2,
  Contrast,
  Crop,
  Database,
  Dice5,
  Download,
  Droplets,
  Eye,
  FileCode2,
  FileImage,
  FilePen,
  FileText,
  Film,
  Fingerprint,
  FlipHorizontal,
  Gamepad2,
  GitCompare,
  Hash,
  Image,
  Images,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  Link as LinkIcon,
  ListFilter,
  Map,
  Minimize2,
  MousePointer,
  MoveDiagonal,
  Newspaper,
  Palette,
  Pentagon,
  PieChart,
  Pipette,
  Printer,
  QrCode,
  Radius,
  RectangleHorizontal,
  RefreshCw,
  RotateCw,
  Scaling,
  ScanBarcode,
  ScrollText,
  Search,
  Share2,
  ShieldCheck,
  Smile,
  Sparkles,
  Square,
  SwatchBook,
  Table2,
  Tags,
  Terminal,
  Timer,
  TrendingUp,
  Type,
  Upload,
  UserRound,
  Wand2,
  Wind,
  type LucideIcon,
} from "lucide-react";

export const LIBRARY_LINKS = [
  { href: "/colors", title: "Colors", fullTitle: "Color Library", icon: Library },
  { href: "/brands", title: "Brands", fullTitle: "Brand Colors", icon: Building2 },
  { href: "/color-names", title: "Names", fullTitle: "Color Names", icon: Type },
  { href: "/gradient-library", title: "Gradients", fullTitle: "Gradient Library", icon: Blend },
  { href: "/palette-library", title: "Palettes", fullTitle: "Palette Library", icon: SwatchBook },
  { href: "/image-tools", title: "Images", fullTitle: "Image Tools", icon: Image },
  { href: "/developers", title: "Dev", fullTitle: "Developers", icon: Terminal },
  { href: "/blog", title: "Blog", fullTitle: "Blog", icon: BookOpen },
] as const;

export const COLOR_CODE_NAV = [
  { href: "/color-codes", title: "All color codes" },
  { href: "/color-codes/common", title: "Common" },
  { href: "/colors/css", title: "HTML/CSS" },
  { href: "/colors/web-safe", title: "Web Safe" },
  { href: "/colors/tailwind", title: "Tailwind" },
  { href: "/colors/material", title: "Material" },
  { href: "/colors/flat-ui", title: "Flat UI" },
  { href: "/color-codes/minecraft", title: "Minecraft" },
  { href: "/color-codes/bukkit", title: "Bukkit" },
  { href: "/color-codes/roblox", title: "Roblox" },
] as const;

export const PRIMARY_NAV = [
  { href: "/colors", title: "Colors" },
  { href: "/tools", title: "Tools" },
  { href: "/color-codes", title: "Color Codes", children: COLOR_CODE_NAV },
  { href: "/colors/tailwind", title: "Design Systems" },
  { href: "/brands", title: "Brands" },
  { href: "/ai-color-copilot", title: "AI" },
  { href: "/learning", title: "Learn" },
] as const;

export const HEADER_LIBRARY_LINKS = LIBRARY_LINKS.filter((item) => item.href !== "/blog");

export const SECONDARY_NAV = [
  { href: "/developers", title: "Developer" },
  { href: "/color-names", title: "Color Names" },
  { href: "/palette-library", title: "Palettes" },
  { href: "/gradient-library", title: "Gradients" },
] as const;

export const TOOL_ICONS: Record<string, LucideIcon> = {
  Pipette,
  ArrowLeftRight,
  RefreshCw,
  Printer,
  Blend,
  Code2,
  MoveDiagonal,
  Circle,
  PieChart,
  SwatchBook,
  Dice5,
  Palette,
  Wind,
  Boxes,
  Type,
  CircleDot,
  Contrast,
  Accessibility,
  Eye,
  Image,
  Images,
  Link: LinkIcon,
  FileImage,
  Download,
  Upload,
  Braces,
  Square,
  Sparkles,
  Layers,
  RectangleHorizontal,
  Radius,
  Pentagon,
  RotateCw,
  Film,
  Baseline,
  Lightbulb,
  TrendingUp,
  BadgeCheck,
  LayoutDashboard,
  LayoutGrid,
  Timer,
  MousePointer,
  ScrollText,
  ListFilter,
  ArrowUpDown,
  FileText,
  Binary,
  Smile,
  Hash,
  FileCode2,
  FilePen,
  GitCompare,
  Database,
  KeyRound,
  Fingerprint,
  QrCode,
  ScanBarcode,
  Minimize2,
  Scaling,
  Droplets,
  Crop,
  FlipHorizontal,
  Bot,
  Map,
  Tags,
  Share2,
  AppWindow,
  Clapperboard,
  AlignLeft,
  Newspaper,
  ShieldCheck,
  UserRound,
  Clock,
  Table2,
  Gamepad2,
  Search,
  Wand2,
};
