import {
  Accessibility,
  AlignLeft,
  AppWindow,
  ArrowLeftRight,
  ArrowUpDown,
  BadgeCheck,
  Baseline,
  Binary,
  Blend,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Building2,
  Circle,
  CircleDot,
  Clapperboard,
  Clock,
  Code2,
  Contrast,
  Crop,
  Database,
  Dice5,
  Download,
  Droplets,
  Eye,
  FileCode2,
  FileImage,
  FilePen,
  FileText,
  Film,
  Fingerprint,
  FlipHorizontal,
  GitCompare,
  Hash,
  Image,
  Images,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  Lightbulb,
  Link as LinkIcon,
  ListFilter,
  Map,
  Minimize2,
  MousePointer,
  MoveDiagonal,
  Newspaper,
  Palette,
  Pentagon,
  PieChart,
  Pipette,
  Printer,
  QrCode,
  Radius,
  RectangleHorizontal,
  RefreshCw,
  RotateCw,
  Scaling,
  ScanBarcode,
  ScrollText,
  Share2,
  ShieldCheck,
  Smile,
  Sparkles,
  Square,
  SwatchBook,
  Tags,
  Terminal,
  Timer,
  TrendingUp,
  Type,
  Upload,
  UserRound,
  Wind,
  type LucideIcon,
} from "lucide-react";

export const LIBRARY_LINKS = [
  { href: "/colors", title: "Colors", fullTitle: "Color Library", icon: Library },
  { href: "/brands", title: "Brands", fullTitle: "Brand Colors", icon: Building2 },
  { href: "/color-names", title: "Names", fullTitle: "Color Names", icon: Type },
  { href: "/gradient-library", title: "Gradients", fullTitle: "Gradient Library", icon: Blend },
  { href: "/palette-library", title: "Palettes", fullTitle: "Palette Library", icon: SwatchBook },
  { href: "/image-tools", title: "Images", fullTitle: "Image Tools", icon: Image },
  { href: "/developers", title: "Dev", fullTitle: "Developers", icon: Terminal },
  { href: "/blog", title: "Blog", fullTitle: "Blog", icon: BookOpen },
] as const;

export const TOOL_ICONS: Record<string, LucideIcon> = {
  Pipette,
  ArrowLeftRight,
  RefreshCw,
  Printer,
  Blend,
  Code2,
  MoveDiagonal,
  Circle,
  PieChart,
  SwatchBook,
  Dice5,
  Palette,
  Wind,
  Boxes,
  Type,
  CircleDot,
  Contrast,
  Accessibility,
  Eye,
  Image,
  Images,
  Link: LinkIcon,
  FileImage,
  Download,
  Upload,
  Braces,
  Square,
  Sparkles,
  Layers,
  RectangleHorizontal,
  Radius,
  Pentagon,
  RotateCw,
  Film,
  Baseline,
  Lightbulb,
  TrendingUp,
  BadgeCheck,
  LayoutDashboard,
  Timer,
  MousePointer,
  ScrollText,
  ListFilter,
  ArrowUpDown,
  FileText,
  Binary,
  Smile,
  Hash,
  FileCode2,
  FilePen,
  GitCompare,
  Database,
  KeyRound,
  Fingerprint,
  QrCode,
  ScanBarcode,
  Minimize2,
  Scaling,
  Droplets,
  Crop,
  FlipHorizontal,
  Bot,
  Map,
  Tags,
  Share2,
  AppWindow,
  Clapperboard,
  AlignLeft,
  Newspaper,
  ShieldCheck,
  UserRound,
  Clock,
};
