/** @type {import('next-sitemap').IConfig} */
/**
 * Do not write public/sitemap.xml — that file overrides App Router src/app/sitemap.ts.
 * Sitemaps are generated by Next from src/app/sitemap.ts.
 */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://colorbase.in",
  generateRobotsTxt: false,
  generateIndexSitemap: false,
  exclude: ["/*"],
  outDir: "sitemap-out",
};
