import { jsPDF } from "jspdf";
import type { TableDocument } from "./types";
import { exportHtml } from "./export";

function slugify(name: string) {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "table";
}

/**
 * Build a printable PDF from the current table (text-based layout).
 * Works offline in the browser without a server.
 */
export async function downloadTablePdf(doc: TableDocument) {
  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 36;
  const usableWidth = pageWidth - margin * 2;

  const visibleRows = doc.rows.map((row) => row.filter((c) => !c.hidden).map((c) => c.value || " "));
  if (!visibleRows.length) {
    throw new Error("Table is empty");
  }

  const colCount = Math.max(...visibleRows.map((r) => r.length), 1);
  const colWidth = usableWidth / colCount;
  const fontSize = Math.min(10, Math.max(7, Math.floor(colWidth / 8)));
  const lineHeight = fontSize + 6;
  const cellPad = 4;

  const footerY = pageHeight - 16;
  const contentBottom = pageHeight - 28;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text(doc.name || "Table", margin, margin - 8);

  pdf.setFontSize(fontSize);
  let y = margin + 12;

  const drawRow = (cells: string[], header: boolean) => {
    // Measure wrapped lines per cell
    const linesPerCell = cells.map((text) =>
      pdf.splitTextToSize(String(text), colWidth - cellPad * 2) as string[]
    );
    const rowLines = Math.max(1, ...linesPerCell.map((l) => l.length));
    const rowHeight = rowLines * lineHeight + cellPad * 2;

    if (y + rowHeight > contentBottom) {
      pdf.addPage();
      y = margin;
    }

    if (header) {
      pdf.setFillColor(225, 29, 72);
      pdf.rect(margin, y, usableWidth, rowHeight, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
    } else {
      pdf.setDrawColor(226, 232, 240);
      pdf.setFillColor(255, 255, 255);
      pdf.rect(margin, y, usableWidth, rowHeight, "FD");
      pdf.setTextColor(15, 23, 42);
      pdf.setFont("helvetica", "normal");
    }

    for (let c = 0; c < colCount; c++) {
      const x = margin + c * colWidth;
      pdf.setDrawColor(226, 232, 240);
      pdf.line(x, y, x, y + rowHeight);
      const lines = linesPerCell[c] ?? [""];
      let ty = y + cellPad + fontSize;
      for (const line of lines) {
        pdf.text(line, x + cellPad, ty);
        ty += lineHeight;
      }
    }
    pdf.line(margin + usableWidth, y, margin + usableWidth, y + rowHeight);
    y += rowHeight;
  };

  visibleRows.forEach((row, i) => {
    const padded = Array.from({ length: colCount }, (_, c) => row[c] ?? "");
    drawRow(padded, Boolean(doc.hasHeader && i === 0));
  });

  // Footer on every page
  const pageCount = pdf.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    pdf.setPage(p);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    pdf.text("Generated by colorbase.in", pageWidth / 2, footerY, { align: "center" });
  }

  pdf.save(`${slugify(doc.name)}.pdf`);
}

/** Optional: open a print window with full styled HTML (Save as PDF). */
export function printTableAsPdf(doc: TableDocument) {
  const html = exportHtml(doc, true);
  const win = window.open("", "_blank", "noopener,noreferrer,width=1024,height=768");
  if (!win) throw new Error("Popup blocked — allow popups to print/save PDF");
  win.document.write(
    `<!DOCTYPE html><html><head><title>${doc.name}</title>
    <style>@media print { .no-print { display: none !important; } body { margin: 24px; } footer { margin-top: 24px; text-align: center; font-size: 12px; color: #64748b; } }</style>
    </head><body>${html}
    <footer>Generated by colorbase.in</footer>
    <script>window.onload=()=>{window.print();}</script></body></html>`
  );
  win.document.close();
}
